apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-operator
  namespace: redis-operator
  labels:
    app.kubernetes.io/name: redis-operator
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-operator
